# Generated by Django 4.1 on 2022-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('content', models.TextField(blank=True, verbose_name='Отзыв')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
