# Generated by Django 4.1 on 2022-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_review_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
        ),
    ]
