# Generated by Django 4.1 on 2022-09-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_call'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
